# Generated by Django 3.0.4 on 2020-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos/'),
        ),
    ]
